# Autogenerated wrapper script for SuperLU_DIST_jll for x86_64-apple-darwin-libgfortran4-mpi+mpich
export libsuperlu_dist_Int32, libsuperlu_dist_Int64, pdtest_32, pdtest_64

using OpenBLAS32_jll
using PARMETIS_jll
using METIS_jll
using LLVMOpenMP_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("SuperLU_DIST")
JLLWrappers.@declare_library_product(libsuperlu_dist_Int32, "@rpath/libsuperlu_dist_Int32.8.dylib")
JLLWrappers.@declare_library_product(libsuperlu_dist_Int64, "@rpath/libsuperlu_dist_Int64.8.dylib")
JLLWrappers.@declare_executable_product(pdtest_32)
JLLWrappers.@declare_executable_product(pdtest_64)
function __init__()
    JLLWrappers.@generate_init_header(OpenBLAS32_jll, PARMETIS_jll, METIS_jll, LLVMOpenMP_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libsuperlu_dist_Int32,
        "lib/libsuperlu_dist_Int32.8.2.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsuperlu_dist_Int64,
        "lib/libsuperlu_dist_Int64.8.2.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        pdtest_32,
        "bin/pdtest_32",
    )

    JLLWrappers.@init_executable_product(
        pdtest_64,
        "bin/pdtest_64",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
